version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/Sao_Paulo"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/Sao_Paulo"
    groups:
      patch-and-minor:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "github-actions"
